name: Deploy to sasin91.xyz
on:
  release:
    types: [published]

#  schedule:
#    - cron: '0 0 * * *' # Everyday at 12am

env:
  LARAVEL_ENV_ENCRYPTION_KEY: ${{ secrets.ENV_KEY }}

jobs:
  phplint:
    name: 🔬 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@2.4.0
        with:
          preset: laravel

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    env:
      SSH_PORT: 22
      SSH_HOST: "sasin91.xyz"
      SSH_USER: "app"
      PROJECT: "sasin91.xyz"

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
      - name: 📝 Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');" # sets up env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Install NPM dependencies
        run: npm install
      - name: Compile assets
        run: npm run build

      - name: Publish assets
        run: |
          php artisan livewire:publish --no-ansi

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test --parallel

      - name: 🔐 Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: 📝 Adding Known Hosts
        run: ssh-keyscan -p ${{ env.SSH_PORT }} -H ${{ env.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: ♻️ Deploy with rsync
        run: rsync --archive --progress --xattrs --chown=app:www-data --exclude .git -e "ssh -p ${{ env.SSH_PORT }}" ./ ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:/home/${{ env.SSH_USER }}/${{ env.PROJECT }}

      - name: ⚡️ Restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd /home/${{ env.SSH_USER }}/${{ env.PROJECT }}
            chown $(whoami) . # PM2 doesn't recognize root user from Github Actions
            php artisan migrate --force

